global:
  marketplace-ami: false
  owner: mcguire7@uk.ibm.com
  qsname: ibm-mq-aws-quickstart
  regions:
    - eu-west-1
  reporting: true

tests:
  quickstart-ibm-mqt1:
    parameter_input: ibm-mq-quickstart-master.params.json
    template_file: ibm-mq-quickstart-master.template
